Options:
    Debug:
        onCommand: true
    BlockProtection:
        Building: true
        Breaking: true
        Crafting: true
# The rules above apply to the following conditions
        InArenas: true
        Only_while_ingame: true
        OutsideArenas: true
    Gamemakers_can_edit: true
    During_games:
        kick_on_disconnect: false
        noTeleporting: true # not yet implemented
        nearbyTributeChat: true # not yet implemented
        noMobSpawnInArena: false
Currentgames: []
Game_count: 0
Arenas: {}