# This is the start of a comment. However, I just forgot everyhitng i was going to put here so, fuck it, i'll just keep this.

Options:
    Debug:
        onCommand: false
        onBlockChange: false
    BlockProtection:
        Rules:
            Building_enabled: true
            Breaking_enabled: true
            Crafting_enabled: true
        Conditions:
            InArenas: true
            Only_while_ingame: true
            OutsideArenas: true
        Show_warning_to_players: true
    Gamemakers_can_edit: true
    Arena_Options:
        During_games:
            noMobSpawnInArena: false
            disqualify_on_disconnect: false
            noTeleporting: true
    NearbyTributeChat:
        Enabled: true
        Distances:
            Clear: 24
            Disembodied: 36
            Garbled: 50