Options:
    Debug:
        onCommand: true
        onBlockChange: true
    BlockProtection:
        Building_enabled: true
        Breaking_enabled: true
        Crafting_enabled: true
        InArenas: true
        Only_while_ingame: true
        OutsideArenas: true
        Show_warning_to_players: true
    Gamemakers_can_edit: true
    During_games:
        disqualify_on_disconnect: false
        noTeleporting: true # not yet implemented
        nearbyTributeChat: true # not yet implemented
        noMobSpawnInArena: false
Currentgames: []
Game_count: 0
Arenas: {} #THIS NEEDS TO BE HERE. Represents an empty Map type